# Generated by Django 5.1.2 on 2024-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(choices=[('Tabletop', 'Jeu de plateau'), ('Dvd', 'Dvd'), ('Cd', 'Cd'), ('Livre', 'Livre')]),
        ),
    ]
