# Generated by Django 5.1.2 on 2024-10-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.member'),
        ),
        migrations.AlterField(
            model_name='item',
            name='loandate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
