# Generated by Django 5.1.2 on 2024-10-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(choices=[('Dvd', 'Dvd'), ('Livre', 'Livre'), ('Tabletop', 'Jeu de plateau'), ('Cd', 'Cd')]),
        ),
    ]
